feat(OverlayMode): Rename only-qam to overlay-mode, qam to quick bar
ShadowBlip/OpenGamepadUI pull request #277
Opened 2023-10-08 20:05 UTC by pastaq

This will require an update to any plugin that used add_to_qam as that will now be add_to_quick_bar. We can add a temporary transitional func that includes a deprecation warning to make the transition smoother.

2023-10-09 22:57 UTC, pastaq commented on assets/themes/card_ui-darksoul.tres
> -[ext_resource type="StyleBox" uid="uid://daavpt58e7jlj" path="res://assets/styles/darksoul/quick_access_menu_panel.tres" id="7_1vum8"]
Not sure why this happened, need feedback on how to restore this properly

2023-10-09 22:57 UTC, pastaq commented on assets/themes/card_ui-dracula.tres
> -[ext_resource type="StyleBox" uid="uid://br2w1fnanqkfa" path="res://assets/styles/dracula/quick_access_menu_panel.tres" id="9_5igh1"]
Same as before

2023-10-09 22:58 UTC, pastaq commented on core/global/plugin_loader.gd
> +var plugins := {} # {plugin_id: {plugin.name: "name", plugin.id: "id", store.tags: ["quck_bar", "steam"], ...}
Typo

2023-10-11 00:32 UTC, ShadowApex requested changes

2023-10-11 00:32 UTC, ShadowApex commented on core/main.gd
> +		get_tree().change_scene_to_file("res://core/ui/vapor_ui_ooverlay_mode/overlay_mode_main.tscn")
```suggestion
		get_tree().change_scene_to_file("res://core/ui/card_ui_overlay_mode/card_ui_overlay_mode.tscn")
```

2023-10-11 00:32 UTC, ShadowApex commented on core/main.gd
> +			get_tree().change_scene_to_file("res://core/ui/vapor_ui_ooverlay_mode/overlay_mode_main.tscn")
```suggestion
			get_tree().change_scene_to_file("res://core/ui/vapor_ui_overlay_mode/overlay_mode_main.tscn")
```

2023-10-11 00:32 UTC, ShadowApex commented on core/main.gd
> +			get_tree().change_scene_to_file("res://core/ui/vapor_ui_ooverlay_mode/overlay_mode_main.tscn")
```suggestion
			get_tree().change_scene_to_file("res://core/ui/vapor_ui_overlay_mode/overlay_mode_main.tscn")
```

2023-10-12 03:50 UTC, ShadowApex approved these changes

2023-10-12 04:09 UTC, merged