fix(Target Devices): Dynamically add Capability Mappings
ShadowBlip/OpenGamepadUI pull request #381
Opened 2024-07-31 18:36 UTC by pastaq

- Selecting different target devices will dynamically add capability maps, based on the target device, ensuring every feature works out of the box. These will only be applied if the source capability has not already been mapped in the device profile.

2024-08-01 02:31 UTC, pastaq commented on core/global/platform.gd
> +	elif product_name in [
I was testing on the Ally X and needed it to work. I can move these to a separate PR if desired.

2024-08-02 00:03 UTC, philmmanjaro commented
Tested Inputplumber 2f55df51 combined with a21df1a7. seems to work so far.

2024-08-02 05:58 UTC, ShadowApex approved these changes

2024-08-06 04:36 UTC, ShadowApex commented on core/global/launch_manager.gd
> +	var profile_modifier = target_gamepad
```suggestion
	var profile_modifier := target_gamepad
```

2024-08-06 04:40 UTC, ShadowApex commented on core/global/launch_manager.gd
> +		profile_modifier = settings_manager.get_value("input", "gamepad_profile_target", InputPlumber.DEFAULT_GLOBAL_PROFILE) as String
```suggestion
		profile_modifier = settings_manager.get_value("input", "gamepad_profile_target", "gamepad") as String
```

2024-08-06 04:42 UTC, ShadowApex commented on core/systems/input/events/event.gd
> +		return null
```suggestion
```

2024-08-06 04:43 UTC, ShadowApex requested changes
Few changes required

2024-08-06 05:26 UTC, ShadowApex approved these changes

2024-08-08 23:00 UTC, merged